In [2]:
import numpy as np
import cv2 as cv

def select_img_from_video(input_file, board_pattern, select_all=False, wait_msec=10):
    # Open a video
    video = cv.VideoCapture(input_file)
    assert video.isOpened(), 'Cannot read the given input, ' + input_file

    # Select images
    img_select = []
    while True:
        # Grab an images from the video
        valid, img = video.read()
        if not valid:
            break

        if select_all:
            img_select.append(img)
        else:
            # Show the image
            display = img.copy()
            cv.putText(display, f'NSelect: {len(img_select)}', (10, 25), cv.FONT_HERSHEY_DUPLEX, 0.6, (0, 255, 0))
            cv.imshow('Camera Calibration', display)

            # Process the key event
            key = cv.waitKey(wait_msec)
            if key == 27:                  # 'ESC' key: Exit (Complete image selection)
                break
            elif key == ord(' '):          # 'Space' key: Pause and show corners
                complete, pts = cv.findChessboardCorners(img, board_pattern)
                cv.drawChessboardCorners(display, board_pattern, pts, complete)
                cv.imshow('Camera Calibration', display)
                key = cv.waitKey()
                if key == 27: # ESC
                    break
                elif key == ord('\r'):
                    img_select.append(img) # 'Enter' key: Select the image

    cv.destroyAllWindows()
    return img_select

def calib_camera_from_chessboard(images, board_pattern, board_cellsize, K=None, dist_coeff=None, calib_flags=None):
    # Find 2D corner points from given images
    img_points = []
    for img in images:
        gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        complete, pts = cv.findChessboardCorners(gray, board_pattern)
        if complete:
            img_points.append(pts)
    assert len(img_points) > 0, 'There is no set of complete chessboard points!'

    # Prepare 3D points of the chess board
    obj_pts = [[c, r, 0] for r in range(board_pattern[1]) for c in range(board_pattern[0])]
    obj_points = [np.array(obj_pts, dtype=np.float32) * board_cellsize] * len(img_points) # Must be 'np.float32'

    # Calibrate the camera
    return cv.calibrateCamera(obj_points, img_points, gray.shape[::-1], K, dist_coeff, flags=calib_flags)



if __name__ == '__main__':
    input_file = 'data/chessboard.MP4'
    board_pattern = (10, 7)
    board_cellsize = 0.025

    img_select = select_img_from_video(input_file, board_pattern)
    assert len(img_select) > 0, 'There is no selected images!'
    rms, K, dist_coeff, rvecs, tvecs = calib_camera_from_chessboard(img_select, board_pattern, board_cellsize)

    # Print calibration results
    print('## Camera Calibration Results')
    print(f'* The number of selected images = {len(img_select)}')
    print(f'* RMS error = {rms}')
    print(f'* Camera matrix (K) = \n{K}')
    print(f'* Distortion coefficient (k1, k2, p1, p2, k3, ...) = {dist_coeff.flatten()}')


## Camera Calibration Results
* The number of selected images = 7
* RMS error = 0.7297942137685635
* Camera matrix (K) = 
[[1.15025045e+03 0.00000000e+00 6.59532446e+02]
 [0.00000000e+00 1.16648714e+03 3.69350778e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
* Distortion coefficient (k1, k2, p1, p2, k3, ...) = [-0.0219095   0.38040568 -0.0037804   0.00403314 -0.90375687]


In [8]:
import numpy as np
import cv2 as cv

# The given video and calibration data
input_file = 'data/chessboard.MP4'
K = np.array([[1150.25045, 0, 659.532446],
              [0, 1166.48714, 369.350778],
              [0, 0, 1]])
dist_coeff = np.array([-0.0219095, 0.38040568, -0.0037804, 0.00403314, -0.90375687])
board_pattern = (10, 7)
board_cellsize = 0.025
board_criteria = cv.CALIB_CB_ADAPTIVE_THRESH + cv.CALIB_CB_NORMALIZE_IMAGE + cv.CALIB_CB_FAST_CHECK

# Open a video
video = cv.VideoCapture(input_file)
assert video.isOpened(), 'Cannot read the given input, ' + input_file

# Prepare a 3D box for simple AR
one_back = board_cellsize * np.array([
    [4, 2, -0],
    [7, 2, -0],
    [7, 2, -1],
    [6, 2, -1],
    [6, 2, -5],
    [5, 2, -5],
    [4, 2, -4.25],
    [4.48, 2, -3.61],
    [5, 2, -3.92],
    [5, 2, -1],
    [4, 2, -1]
])
one_front = board_cellsize * np.array([
    [4, 3, -0],
    [7, 3, -0],
    [7, 3, -1],
    [6, 3, -1],
    [6, 3, -5],
    [5, 3, -5],
    [4, 3, -4.25],
    [4.48, 3, -3.61],
    [5, 3, -3.92],
    [5, 3, -1],
    [4, 3, -1]
])

# Prepare 3D points on a chessboard
obj_points = board_cellsize * np.array([[c, r, 0] for r in range(board_pattern[1]) for c in range(board_pattern[0])])

# Run pose estimation
while True:
    # Read an image from the video
    valid, img = video.read()
    if not valid:
        break

    # Estimate the camera pose
    complete, img_points = cv.findChessboardCorners(img, board_pattern, board_criteria)
    if complete:
        ret, rvec, tvec = cv.solvePnP(obj_points, img_points, K, dist_coeff)

        # Draw the box on the image
        line_front, _ = cv.projectPoints(one_front, rvec, tvec, K, dist_coeff)
        line_back, _ = cv.projectPoints(one_back, rvec, tvec, K, dist_coeff)
        
        cv.polylines(img, [np.int32(line_back)], True, (204,255,153), 2)
        cv.polylines(img, [np.int32(line_front)], True, (204,255,153), 2)
        for b, t in zip(line_front, line_back):
            cv.line(img, np.int32(b.flatten()), np.int32(t.flatten()), (204,255,153), 2)

        # Print the camera position
        R, _ = cv.Rodrigues(rvec) # Alternative) scipy.spatial.transform.Rotation
        p = (-R.T @ tvec).flatten()
        info = f'XYZ: [{p[0]:.3f} {p[1]:.3f} {p[2]:.3f}]'
        cv.putText(img, info, (10, 25), cv.FONT_HERSHEY_DUPLEX, 0.6, (0, 255, 0))

    # Show the image and process the key event
    cv.imshow('Pose Estimation (Chessboard)', img)
    key = cv.waitKey(10)
    if key == ord(' '):
        key = cv.waitKey()
    if key == 27: # ESC
        break

video.release()
cv.destroyAllWindows()
